
public enum AGILER {
    BEKAR,
    EVLI_ESI_CALISMAYAN,
    EVLI_ESI_CALISMAYAN_1_COCUKLU,
    EVLI_ESI_CALISMAYAN_2_COCUKLU,
    EVLI_ESI_CALISMAYAN_3_COCUKLU,
    EVLI_ESI_CALISMAYAN_4_COCUKLU,
    EVLI_ESI_CALISMAYAN_5_COCUKLU, 
    EVLI_ESI_CALISAN,
    EVLI_ESI_CALISAN_1_COCUKLU,
    EVLI_ESI_CALISAN_2_COCUKLU,
    EVLI_ESI_CALISAN_3_COCUKLU,
    EVLI_ESI_CALISAN_4_COCUKLU,
    EVLI_ESI_CALISAN_5_COCUKLU,
    
    
    
}
